"""add reset password fields

Revision ID: 1ee143fb9572
Revises: db5a8022b61e
Create Date: 2026-05-01 00:52:35.933206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee143fb9572'
down_revision: Union[str, Sequence[str], None] = 'db5a8022b61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token', sa.String(), nullable=True))
    # op.add_column('user', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_token_expiry')
    op.drop_column('user', 'reset_token')
    # ### end Alembic commands ###
